### ISSUE TITLE
File may be corrupted

### ISSUE THREAD

**Issue by lythm** [milostosic/MTuner#47] opened 2019-08-01 02:39 UTC
I'm use 4.3.1 on windows 10,  error occurred after every capture:

![image](https://user-images.githubusercontent.com/1776973/62261499-21d89d80-b448-11e9-90a3-9340c2234850.png)

captured file
[rendernode.2019.8.1.10.9.43.432.MTuner.zip](https://github.com/milostosic/MTuner/files/3454648/rendernode.2019.8.1.10.9.43.432.MTuner.zip)

**Comment by milostosic** [comment] 2020-02-12 11:31
I've debugged your capture and, besides being tiny, has no valid memory operations inside. How did you create this one?

**Comment by milostosic** [comment] 2020-02-13 09:40
Likely a duplicate of #48 - same reason. Closing for now

**Closed by milostosic** 2020-02-13 09:40 UTC
