### ISSUE TITLE
Windows 10 - "Virus scan failed" or "Virus detected"

### ISSUE THREAD

**Issue by funvill** [milostosic/MTuner#12] opened 2017-08-29 16:23 UTC
**Experienced:**

I attempted to download the mtuner64.msi with Chrome Version 60.0.3112.90 (Official Build) (64-bit) on Windows 10 with windows defender installed. 

Chrome/Windows/Defender blocked the download with the following error message. 

![image](https://user-images.githubusercontent.com/314120/29831906-72bb11be-8c9b-11e7-833d-90b9483eaa4a.png)

> "Virus scan failed" or "Virus detected"

**Expected**

The install file not to detect the install files as a virus.

**Comment by milostosic** [comment] 2017-08-30 00:19
msi file isn't signed and neither is the MTuner exectuble, since certificates are not cheap, this will likely remain so.

**Comment by ericLemanissier** [comment] 2017-09-04 10:05
The virus detection is unrelated to executable signature. What is more, windows defender is not the only one which detects a virus, as can be seen here: https://www.virustotal.com/fr/file/8aa7617ea2e830aa5f5b4ab0f951e1bf0b905d55f95da429114861b154133f92/analysis/1504519168/
The virus seems to be located in MTuner.cab->MtunerCmdl

Please reopen this issue

**Comment by milostosic** [comment] 2017-09-04 22:32
I have both Windows defender and Avast running and can't reproduce this or detect a virus.
In any case, I'll recompile MTunerCmd to double check and possibly re-upload files - if I find anything suspicious.

**Comment by milostosic** [comment] 2017-09-04 23:41
Ok, this is getting weird... office computer does 'detect a virus' with defender.
But, downloading MSI through FTP and installing it gives me the same dir structure as ZIP file, as it should. Here's the weird part - binary compare of those files confirms that all files are identical between MSI and ZIP archives. However, **nothing** is reported for the ZIP file or it's contents when decompressed.

I will remove MSI file for the moment as I don't have time to look into this right now.

**Comment by milostosic** [comment] 2017-09-05 02:57
I was able to track this down to retail configuration of MTuner.com vs release/debug configurations.
Compiling in retail triggers **false positives** by several anti viruses - not really sure why.
I'll upload the "clean" releases later today.

**Comment by milostosic** [comment] 2017-09-05 08:22
Update: turns out command line programs that have no user input or no output tend to trigger this with anti-viruses.  I modified the behavior and it seems to be 'ok' now.
Still need to wait for the new release to finally close this...

**Comment by milostosic** [comment] 2017-09-09 09:09
New release is up, scanned with defender, downloaded fine, etc.
I've scanned unpacked files as well, just to be sure, came out clean.
VirusTotal report is here:
https://www.virustotal.com/#/file/b2787447ea4eed8e7b6ec51f93990c51085efc3b66353bf6b6732480d9309d41/detection

**Closed by milostosic** 2017-09-09 09:09 UTC
