### ISSUE TITLE
MTuner keeps exe locked

### ISSUE THREAD

**Issue by hardliner66** [milostosic/MTuner#56] opened 2020-05-04 20:51 UTC
After profiling, MTuner keeps a lock on the executable. This prevents a rapid test cycle because you have to close MTuner everytime you want to recompile.

Would it be possible to release the file lock after profiling is done?

**Comment by milostosic** [comment] 2020-05-06 03:34
Can you provide more information? What is your workflow? Is the executable locked or PDB files?

**Comment by hardliner66** [comment] 2020-05-06 06:43
Sure.

My workflow is to check whats using too much memory in MTuner, making some changes where I think it would help, recompiling and testing again. Recompiling fails because MTuner kept a lock on the pdb file.

**Comment by milostosic** [comment] 2020-05-06 06:49
Yes, this is by design as otherwise resolving call stacks would be slow. So you need to close the previous capture before being able to recompile.

**Comment by hardliner66** [comment] 2020-05-06 07:05
I have to close the whole application to release the lock on the pdb file. Closing only the last capture doesn't work.

**Comment by hardliner66** [comment] 2020-05-06 07:08
I also just found out, that opening an old capture locks the pdb again. Doesn't that mean that old captures become useless after recompiling? Wouldn't it be better to store that information in the capture itself or make a copy of the pdb into the capture directory?

**Comment by milostosic** [comment] 2020-05-06 07:36
Ok, I'll take a look at the PDB lock. And yes, old captures become useless as the PDB information is no longer valid - storing this information to a capture file is not possible and likely should be handled using symbol servers to match the correct PDB. I never tested this, feel free to give it a try.

**Comment by hardliner66** [comment] 2020-05-06 08:17
I never used symbol servers (except the one from Microsoft). I will look into it.

**Comment by milostosic** [comment] 2020-05-09 13:05
Fixed in v4.4.3

**Closed by milostosic** 2020-05-09 13:05 UTC
