### ISSUE TITLE
MTuner hangs in "Processing" of a snapshot taken of a Debug build

### ISSUE THREAD

**Issue by magcius** [milostosic/MTuner#43] opened 2018-10-01 19:01 UTC
I took a snapshot of a Debug build of our project. MTuner was able to successfully capture a ~250MB mtuner file but it seems to hang indefinitely for me during the Processing stage. I should be able to share the mtuner file privately.

**Comment by milostosic** [comment] 2018-10-05 10:58
I've just uploaded the latest release (v4.1.3), using it I cannot reproduce the problem locally.
I loaded your capture file and could see more than 500K memory operations... 
Could this be related to symbol loading? Maybe downloading PDB files is taking a long time?

**Comment by magcius** [comment] 2018-10-05 15:30
Interesting, maybe this is choking on loading .pdb files. I've left it for over 3 hours without it loading, so I do think this is an infinite loop or hang somewhere.

**Comment by milostosic** [comment] 2018-10-05 16:30
Yes, that much time does imply some dead loop. But I've loaded it just fine, could see which modules you're using (like PhysX, etc.) so the problem is elsewhere...
Since I can't reproduce it, the best would be if you ran MTuner through a debugger and then see where it hangs. Feel free to contact me via e-mail if you need any help with setting this up.

**Comment by magcius** [comment] 2018-10-05 16:34
Indeed, however getting the build environment for MTuner might be a bit tricky. Do you provide debug builds of MTuner?

**Comment by milostosic** [comment] 2018-10-05 16:43
I don't provide debug builds. However, setting up the build environment is actually fairly easy but yet to be fully documented. This is why I'll be happy to help with this. 

Generally speaking this is needed:
 - Install Qt (I use online installer but building from source works too)
 - Set an environment variable for Qt path (needed for [build](https://github.com/milostosic/build))
 - Clone MTuner and dependent repositories
 - Generate projects with [GENie](https://github.com/bkaradzic/GENie)

Obviously, there's a few more details so if you're up for this please let me know and I'll guide you through it.

**Comment by milostosic** [comment] 2018-10-07 11:28
I'll close this now, we can reopen it if you're up for some debugging.

**Closed by milostosic** 2018-10-07 11:28 UTC

**Comment by dcb-framatome** [comment] 2019-05-06 20:19
I'm experiencing the same problem.  If the problem is indeed related to loading PDB files then please provide better documentation as to how to setup PDB lookup.  I would think that MTuner should skip symbol lookup if the PDB is not found or is taking too long to download.

**Comment by dcb-framatome** [comment] 2019-05-07 17:27
I built the debug version of MTuner.  The program get's stuck at line 285 of pdb_file.cpp while loading the PDB file for my application (Qt/QML-based application).  It's been stuck on that line for more than 3 hours.  I also noticed that other PDB files were loaded before this one.  However, the PDB file loading does not update the GUI.  The GUI should be updated after every PDB file is loaded so that it remains responsive.

**Comment by dcb-framatome** [comment] 2019-05-07 17:44
numSymbolsFetched == 1

**Comment by dcb-framatome** [comment] 2019-05-07 18:30
It finally finished loading after 5 hours.  In spite of all the time it took to load symbols, the call stack tree shows all functions as unknown.

**Comment by dcb-framatome** [comment] 2019-05-07 18:32
I take that back.  Opening up the "UNKNOWN's" shows the function calls.
