### ISSUE TITLE
Only "Unknown" entries in call stacks

### ISSUE THREAD

**Issue by Zbyl** [milostosic/MTuner#15] opened 2017-09-07 22:24 UTC
I just tried MTuner on a sample Visual Studio project, with all default settings (including /ZI debug information).
Unfortunately I get only "Unknown" Names in Call Stack Tree and "Unknown" Files and Lines 0 in Stack trace window.

The .pdb file is found, I think, because MTuner locks the .pdb file, so that it's not writable.
I also tried using my own symbol server - no difference.

I thought it might be some problem with using VS 2017, so I tried with VS 2015, but same problem.

**Comment by milostosic** [comment] 2017-09-07 22:37
Not the first time I get a report like this so there must be some issue lurking.
Is there any other information you could provide? Can you reproduce the problem with MTuner SDK samples?

**Comment by Zbyl** [comment] 2017-09-07 23:02
On both MTunerLinkerExampleDebug.exe (Debug/x64) and MTunerManualExampleDebug.exe (Debug/x64) everything works fine.

**Comment by Zbyl** [comment] 2017-09-07 23:11
I have found the problem:
I get "Unknowns" when Generate Debug Info is set to "Optimize for faster linking" (/DEBUG:FASTLINK).
When I change it to "Optimize for debugging" (/DEBUG) I get all call stacks.

**Comment by Zbyl** [comment] 2017-09-07 23:44
Further conclusions:
When compiling with VS 2015 stack traces work only when /DEBUG:FASTLINK is not specified.
When compiling with VS 2017 stack traces don't work.

**Comment by milostosic** [comment] 2017-09-08 00:10
Thank you for the details! Finally something I can debug :)
I've never used FASTLINK so that explains why I couldn't reproduce it.

**Comment by milostosic** [comment] 2017-09-11 03:49
Tested with latest code, I can get debug symbols for projects compiled with VS2017 just fine.
FASTLINK linker option removes much of the PDB file (all private symbols) so it's not possible to get symbol information. I'll close the issue.

**Closed by milostosic** 2017-09-11 03:49 UTC
